1250 cypress organizational structure
bratislava/bratislava.sk pull request #1258
Opened 2024-05-02 10:42 UTC by karolinavor

2024-05-02 21:25 UTC, sebastian-vass requested changes

2024-05-02 21:25 UTC, sebastian-vass commented on tests/cypress/e2e/organizationalStructure.cy.ts
>              cy.wrap(Cypress.$(`[data-cy=structure-accordion-card-name]`, content)).should('contain', 'Vallo Matúš, Ing. arch.')
Is it necessary to have this twice?

2024-05-02 21:25 UTC, sebastian-vass commented on tests/cypress/e2e/organizationalStructure.cy.ts
> +              cy.wrap(Cypress.$(`[data-cy=structure-accordion-card-email-mobile]`, content)).should('contain', 'primator@bratislava.sk')
I run into a problem at this point. Same problem for desktop.
wrap: jQuery{0}

2024-05-06 12:02 UTC, radoslavzeman commented
Hello,
as of today, the url and headline for organisational structure page changed.

Url:
- from `https://bratislava.sk/mesto-bratislava/sprava-mesta/magistrat/organizacna-struktura-a-kontakty`
- to `https://bratislava.sk/mesto-bratislava/sprava-mesta/magistrat/organizacna-struktura`

Headline:
- from "Organizačná štruktúra a kontakty"
- to "Organizačná štruktúra"

2024-05-11 09:31 UTC, sebastian-vass approved these changes

2024-05-11 09:32 UTC, merged