BA-682 Change translations and url in road closures section
bratislava/bratislava.sk pull request #310
Opened 2022-09-02 17:47 UTC by JacobMu

JIRA ticket: https://inovaciebratislava.atlassian.net/browse/BA-682

I changed translations for section tab title and button for more news in the bottom part of the section. Plus, extracted logic for similar two tabs that shared similar design to one component.

2022-10-03 14:10 UTC, Balros requested changes

2022-10-03 14:26 UTC, Balros commented
Also we recently switched to using strict typescript. We are not switching whole project  to strict in one step but we are switching gradually. Therefore please erase first line(`// @ts-strict-ignore`) of all files you touched and resolve any issues that comes up.

Same thing for eslint errors. Erase all comments which disables eslint rules at the begining of the file and resolve any issues that comes up.

2023-02-02 08:40 UTC, mpinter approved these changes
When I'm on large screen I get different message on closures than on smaller ones - I assume this is by accident and the large one is incorrect:

<img width="1163" alt="Screenshot 2023-02-02 at 09 36 56" src="https://user-images.githubusercontent.com/2327312/216273454-717aa7f7-3811-4038-85bd-3c1257280c31.png">

<img width="977" alt="Screenshot 2023-02-02 at 09 37 18" src="https://user-images.githubusercontent.com/2327312/216273520-8383434f-a05a-458e-a880-10ab55ea7bea.png">

Please also see the comment on exporting functions vs a static object, but otherwise looks ok - look at these two before merging but you can merge without further review.

2023-03-07 12:51 UTC, radoslavzeman commented
Outdated. The section will undergo redesign.

2023-03-07 12:51 UTC, closed without merging