FORM-174: Add DatePicker component, add to styleguide page examples
bratislava/bratislava.sk pull request #339
Opened 2022-10-11 16:41 UTC by AntonZezul

2022-10-11 16:57 UTC, AntonZezul commented
Problem with TypeScript strict mode

2022-10-12 07:28 UTC, mpinter requested changes
:+1: really nice work, just fix the ts issues & move the colors to global config & we're ready to 🚢 

leaving on 'requested changes' as I want to take a quick look at the colors config once it's here, but the second review should go through quickly

2022-10-12 07:28 UTC, mpinter commented on next/components/forms/DatePicker/Calendar/Calendar.tsx
> +        <Button onPress={onSubmit} text="Potvrdiť" variant="black" size="sm" />
we should use i18n libraries for these texts - currently we lack the setup we need for the forms part, so no action required in this PR, just noting there will be a followup

2022-10-13 13:04 UTC, mpinter approved these changes
✅

2022-10-13 14:29 UTC, merged