basic style for alert component
bratislava/bratislava.sk pull request #349
Opened 2022-10-17 16:40 UTC by AkihitoVM

2022-10-20 10:49 UTC, mpinter requested changes
- code styling & newlines at the ends of files
- the styles do not match figma exactly (i.e. check font weight on the buttons or padding on bottom of alert without buttons)

2022-10-21 08:47 UTC, mpinter requested changes
The font weights are still incorrect - you should always check the styling against figma:

<img width="917" alt="Screenshot 2022-10-21 at 10 31 14" src="https://user-images.githubusercontent.com/2327312/197153194-cbfb0b2f-2999-4465-ab3e-6be556196ed3.png">

<img width="1455" alt="Screenshot 2022-10-21 at 10 31 37" src="https://user-images.githubusercontent.com/2327312/197153220-1a911e21-9cb4-4dfd-a232-23e55c53377b.png">

I.e. the button & the title are wrong. I also see that the gaps (or paddings/margins) between sections inside the alert are wrong - we're being a bit more lenient with these as this can get easier together with fixing the tailwind config (will write regarding this to slack). Still, in case you're doing those 'by eye' for them to roughly match the design, please again - look at the exact numbers in figma and try to follow those.

2022-10-21 09:11 UTC, AkihitoVM commented
> The font weights are still incorrect - you should always check the styling against figma:
> 
> <img alt="Screenshot 2022-10-21 at 10 31 14" width="917" src="https://user-images.githubusercontent.com/2327312/197153194-cbfb0b2f-2999-4465-ab3e-6be556196ed3.png">
> 
> <img alt="Screenshot 2022-10-21 at 10 31 37" width="1455" src="https://user-images.githubusercontent.com/2327312/197153220-1a911e21-9cb4-4dfd-a232-23e55c53377b.png">
> 
> I.e. the button & the title are wrong. I also see that the gaps (or paddings/margins) between sections inside the alert are wrong - we're being a bit more lenient with these as this can get easier together with fixing the tailwind config (will write regarding this to slack). Still, in case you're doing those 'by eye' for them to roughly match the design, please again - look at the exact numbers in figma and try to follow those.

Ako som spominal na calle, typ takeho buttonu nie je implementovany v ramci Buttonov vo figme, je to iba vzorec vyuzitia tlačitka.

2022-10-28 12:57 UTC, mpinter approved these changes
:+1: lgtm

2022-10-28 12:57 UTC, mpinter commented on next/tailwind.config.js
> +        3: '13px'
still not convinced about this one but let's deal with it in the global spacing rewrite (will create a JIRA task today)

2022-10-28 14:58 UTC, merged