FORM-221: test workflow
bratislava/bratislava.sk pull request #451
Opened 2022-12-12 10:52 UTC by kristianduda

2022-12-19 16:35 UTC, mpinter requested changes
`Error: Unhandled error: TypeError: core.notice is not a function`

is there some setup you will need from us ?

2022-12-19 20:02 UTC, kristianduda commented
Seems related to no change in src.

2022-12-21 15:26 UTC, mpinter approved these changes

2022-12-21 15:26 UTC, mpinter commented on next/README.md
> +# Bratislava.sk
```suggestion
# Bratislava.sk
```

2022-12-21 15:39 UTC, merged