Form-184/Fix: Label warning
bratislava/bratislava.sk pull request #469
Opened 2022-12-20 13:59 UTC by ValeriiMedvezhonkov

Fix: Label warning, and custom width of progress bar was decreased because of on small displays it went beyond

2022-12-21 15:32 UTC, mpinter requested changes
This means if I don't supply label I will get an ugly id written into a span above the progress bar - that's probably not intended.

2022-12-22 15:15 UTC, ValeriiMedvezhonkov commented
> This means if I don't supply label I will get an ugly id written into a span above the progress bar - that's probably not intended.

No, we render label ONLY if we put it as a prop, otherwise we need to add some labelId to useProgressBar hook. we don't get any ugly id on top of progress bar 
<img width="369" alt="image" src="https://user-images.githubusercontent.com/65829237/209164923-64ff680f-dd25-427a-9f61-095e952882b1.png">

2022-12-23 08:48 UTC, mpinter commented
> > This means if I don't supply label I will get an ugly id written into a span above the progress bar - that's probably not intended.
> 
> No, we render label ONLY if we put it as a prop, otherwise we need to add some labelId to useProgressBar hook. we don't get any ugly id on top of progress bar, or you can just take a look on a styleguide, how it looks when progress bar doesn't contain any label <img alt="image" width="369" src="https://user-images.githubusercontent.com/65829237/209164923-64ff680f-dd25-427a-9f61-095e952882b1.png">

Ah, sorry, misread the change, thought the `label: label ?? uuidv4(),` is in params not in `useProgressBar` hook.

All good then, LGTM

2022-12-23 08:49 UTC, mpinter approved these changes

2022-12-23 11:45 UTC, merged