Form-240/RJSF-FieldGroups
bratislava/bratislava.sk pull request #513
Opened 2023-01-17 16:36 UTC by ValeriiMedvezhonkov

dateFromTo,timeFromTo,dateTime,doubledInput field group widgets

2023-01-19 13:38 UTC, mpinter requested changes
Please test thoroughly - there are multiple issues with filling in those fields, resubmit when you are certain that they behave as they should.

2023-01-19 13:38 UTC, mpinter commented on next/components/forms/widget-components/DateTimePicker/TimeSelector.tsx
> +        : 0
missed this on last review - but again, this is much nicer with ?.


```suggestion
      hoursItemRef?.current?.[+timeFormatArray[0]]?.offsetTop || 0
```

2023-01-19 13:38 UTC, mpinter commented on next/components/forms/widget-components/DateTimePicker/TimeSelector.tsx
> +        : 0
```suggestion
      minutesItemRef?.current?.[+timeFormatArray[1]]?.offsetTop || 0
```

2023-01-19 13:38 UTC, mpinter commented on next/components/forms/widget-components/DateTimePicker/TimeSelector.tsx
> +                      (minValueArray && minValueArray[0] < timeFormatArray[0]) ||
```suggestion
                      (minValueArray?.[0] < timeFormatArray[0]) ||
```

elsewhere as well

2023-01-26 20:16 UTC, ValeriiMedvezhonkov commented
@mpinter 
this PR includes much more work than it should(need to have separate tasks, but ok), was tested all date and time pickers [also in field group with From-To logic]. Also I reviewed and found UI bug with field aligning and error messages direct in components so I decided to write custom logic to display erorr messages in Field-Group components. ( to save tester time in a future)

- * One bug still ( actually not a bug a small mistake in time format) exist in time picker. If I type a time in a field ( not via popup) for example in a H:MM for example "4:15" ( correct time format will be "04:15") format and go next (**_Question:_** correct time format is HH:MM ???? ) in a formData object it will be in H:MM format instead of HH:MM, but after revisiting page (Go previous) time format will be changed in a correct way, I tried to do some hack like 'componentWillUnmount' in a functional component but it didn't work, so I left as it is.

- * For Date and Time field-group widgets was changed logic and now we MUST use predefined keys such as [startDate-endDate or startTime-endTime]. Maybe we can deal in this way in other components ( not only for this 4 component, I mean InputSelectWidget and so on). If so, we can solve the problem with indexas for fields.

2023-01-27 10:43 UTC, mpinter requested changes
Can't get to 3rd step, will be shown this error:

<img width="1123" alt="Screenshot 2023-01-27 at 11 41 31" src="https://user-images.githubusercontent.com/2327312/215067263-f4de6f9a-febe-40ee-a3f0-1e78c2f99e7b.png">

When I click on 'next' and the validation does not pass, the data in whole step will be reset to their initial value, this is not wanted.

2023-01-27 10:43 UTC, mpinter commented on next/pages/form/[eform].tsx
> +        form?.currentSchema?.properties[key]?.dateFromTo &&
this assumes this data lives only on 'top level' of each step, which might not be true. But same issue is in the other validation, I'm ok with fixing this all at once and keeping like this for now, just pointing this out.

2023-01-27 10:55 UTC, ValeriiMedvezhonkov commented
> 

maybe you forgot to pull last changes, or try to remove node_monudeles and install once again ( idk where is problem cause I tested it ant its works fine.

2023-01-30 16:55 UTC, mpinter approved these changes
alright, pulled again, restarted the server, all works

let's 🚢 (finally! 🙂)

2023-01-30 19:37 UTC, merged